services:
  web_server:
    build: .
    ports:
      - ${WEB_SERVER_PORT}:3000
    depends_on:
      - database
      #- redis
    container_name: toprecipe-webserver
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - ./toprecipe:/pm2.json
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  database:
    image: yobasystems/alpine-mariadb:10.11.8
    container_name: toprecipe-db
    ports:
      - "2222:3306"
    #restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=UTC
    volumes:
     - ./data/db/mysql:/var/lib/mysql

# networks:
    #   - app-network

  # esto sera para enlazar con la app
  # app:
  #   image: 
  #   container_name: topRecipe-app
  #   environment:
  #     DB_HOST: database
  #     DB_DATABASE: ${MYSQL_DATABASE}
  #     DB_USER: ${MYSQL_USER}
  #     DB_PASSWORD: ${MYSQL_PASSWORD}
  #     DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     DB_PORT: 3306
  #   depends_on:
  #     - database
  #   networks:
  #     - app-network

  # networks:
  #   app-network: 
  #     driver: bridge