services:
  web_server:
    build: ./top_recipe_docker
    ports:
      - ${WEB_SERVER_PORT}:3000
    depends_on:
      - database
    container_name: toprecipe-webserver
    working_dir: /web
    command: npm run start:dev
    volumes:
      - ./top_recipe_docker:/web
    environment:
      - TZ=Europe/Berlin

  database:
    image: yobasystems/alpine-mariadb:10.11.8
    container_name: toprecipe-db
    ports:
      - "2222:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Berlin
    volumes:
      - ./top_recipe_docker/data/db/mysql:/var/lib/mysql

# networks:
    #   - app-network

  # esto sera para enlazar con la app
  # app:
  #   image: 
  #   container_name: topRecipe-app
  #   environment:
  #     DB_HOST: database
  #     DB_DATABASE: ${MYSQL_DATABASE}
  #     DB_USER: ${MYSQL_USER}
  #     DB_PASSWORD: ${MYSQL_PASSWORD}
  #     DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     DB_PORT: 3306
  #   depends_on:
  #     - database
  #   networks:
  #     - app-network

  # networks:
  #   app-network: 
  #     driver: bridge