services:
  web_server:
    container_name: toprecipe-webserver
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - ${WEB_SERVER_PORT}:3000
    volumes:
      - ./TopReceit_Docker:/web
    working_dir: /web
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - TZ=Europe/Berlin
    networks:
      - toprecipe-network

  database:
    container_name: toprecipe-db
    image: mysql:8.0
    ports:
      - "2222:3306"
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Berlin
    volumes:
      - ./TopReceit_Docker/data/db/mysql:/var/lib/mysql
    networks:
      - toprecipe-network

  phpmyadmin:
    container_name: toprecipe-phpmyadmin
    image: phpmyadmin:latest
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - toprecipe-network

networks:
  toprecipe-network:
    driver: bridge